### ISSUE TITLE
Add CI/CD to project

### ISSUE THREAD

**Issue by QubitPi** [paion-data/screwdriver-cd-homepage#2]
1. Create a directory called `.github` under project root
2. Create a sub-directory named `workflows` under `.github` directory
3. Create a file called `ci-cd.yml` in `workflows` directory with the following content:

   ```yaml
   # Copyright Paion Data
   ---
   name: CI/CD

   'on':
     pull_request:
     push:
       branches:
         - master

   jobs:
     homepage-build:
       name: Tests Homepage Build
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: ruby/setup-ruby@v1
           with:
             ruby-version: '3.0'
         - run: |
             gem install jekyll
             bundle install
             bundle exec jekyll build
```
